name: release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        distribution: 'adopt'
        java-version: 11
    - name: Build with Gradle
      run: chmod +x ./gradlew && ./gradlew assembleRelease
    - name: Publish package
      run: gradle publish
      env:
        GITHUB_USERNAME: ${{ secrets.USERNAME }}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}